name: Deploy HTML to GitHub Pages

on:
  push:
    branches: [ "main" ]
  
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # If you need to build (e.g., for frameworks like Jekyll, React, etc.)
      # Add build steps here. For plain HTML, this isn't needed
      # - name: Setup Node
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 18
      # - run: npm install && npm run build

      - name: Upload HTML artifact
        uses: actions/upload-pages-artifact@v2
        with:
          # Upload entire repository (or specify path to your HTML file)
          path: ./
          # If you only want to upload specific files:
          # path: |
          #   index.html
          #   assets/
          #   style.css

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
